services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pg-educ
      POSTGRES_PASSWORD: pg-educ
      POSTGRES_DB: pg-educ
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/bitnami/redis/data
    ports:
      - "6379:6379"

  redisInsight:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  data: {}
  postgres-data: {}
