services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/bitnami/redis/data
    ports:
      - "6379:6379"
  redisInsight:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  data: {}
